# Site settings
title: Nick Aversano
email: nospam+at+nickaversano.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickaversano.com" # the base hostname & protocol for your site
twitter_username: nickaversano
github_username:  nickaversano
spotify_username: 121907576
linkedin_profile: https://www.linkedin.com/pub/nick-aversano/39/704/24b
tag_colors:
  design: E74C3C
  development: 3498DB
  video: 2ECC71

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
collections:
  projects:
    output: true
    permalink: /:title/