---
title: Nick Aversano
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:title/"
  uploads:
    title: Uploads
    output: true
email: nospam+at+nickaversano.com
description: |
  Hi, I'm Nick. I create websites, develop apps, shoot videos, design things, and make games.
baseurl: ''
url: http://nickaversano.com
twitter_username: nickaversano
github_username: nickaversano
spotify_username: 121907576
linkedin_profile: https://www.linkedin.com/pub/nick-aversano/39/704/24b
tag_colors:
  design: E74C3C
  development: 3498DB
  video: 2ECC71
markdown: kramdown
permalink: "/:title/"
paginate: 6
